name: Auto-Merge Develop to Main
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

# Add permissions section
permissions:
  contents: write

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Check for changes in develop
        id: check_changes
        run: |
          git fetch origin develop
          DIFF_COUNT=$(git rev-list --count HEAD..origin/develop)
          echo "diff_count=$DIFF_COUNT" >> $GITHUB_OUTPUT

      - name: Merge develop into main
        if: steps.check_changes.outputs.diff_count != '0'
        run: |
          git merge --no-ff origin/develop -m "Auto-merge develop into main (scheduled)"
          git push origin main
